security:

    providers:
        administrators:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            provider: administrators
            pattern: ^/admin|^/inside
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: home
                always_use_default_target_path: true
            logout:
                path: logout
                target: homepage

        main:
            anonymous: ~
